# Data Types - Matrices

In [12]:
# Creating Matrices

# Method 1
x <- matrix(nrow=3,ncol=3)
print(x)
print(dim(x))
print(attributes(x))

# Method 2
x <- matrix(1:9,nrow = 3,ncol = 3)
print(x)

# Method 3
m <- 1:10
dim(m) <- c(2,5)
print(m)

# Method 4
x <- 1:5
y <- 1:5
m <- cbind(x,y)
print(m)
m <- rbind(x,y)
print(m)

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[3,]   NA   NA   NA
[1] 3 3
$dim
[1] 3 3

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
     x y
[1,] 1 1
[2,] 2 2
[3,] 3 3
[4,] 4 4
[5,] 5 5
  [,1] [,2] [,3] [,4] [,5]
x    1    2    3    4    5
y    1    2    3    4    5


# Data Types - Factors

In [15]:
# Create Factors
x <- factor(c("yes","yes","no","no"))
print(x)

[1] yes yes no  no 
Levels: no yes


In [17]:
table(x) # Prints the aggregation of the values.

x
 no yes 
  2   2 

In [22]:
print(unclass(x)) # Gives the details of factor x.

[1] 2 2 1 1
attr(,"levels")
[1] "no"  "yes"


In [27]:
# Implicitly R sets levels of factors alphabetically.
# To explicitly Set level of factors
x <- factor(c("yes","yes","no","no"),levels=c("yes","no")) 
print(x)

[1] yes yes no  no 
Levels: yes no


# Data Types - Missing Values

In [37]:
# NaN is NA but NA is not NaN.
x = c(1,2,3,NA,NaN,NA)
print(is.na(x)) # Used to test objects if they are NA.
print(is.nan(x)) # Used to test objects if they are NAN.

[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE
[1] FALSE FALSE FALSE FALSE  TRUE FALSE
