# Data Types - Matrices

In [12]:
# Creating Matrices

# Method 1
x <- matrix(nrow=3,ncol=3)
print(x)
print(dim(x))
print(attributes(x))

# Method 2
x <- matrix(1:9,nrow = 3,ncol = 3)
print(x)

# Method 3
m <- 1:10
dim(m) <- c(2,5)
print(m)

# Method 4
x <- 1:5
y <- 1:5
m <- cbind(x,y)
print(m)
m <- rbind(x,y)
print(m)

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[3,]   NA   NA   NA
[1] 3 3
$dim
[1] 3 3

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
     x y
[1,] 1 1
[2,] 2 2
[3,] 3 3
[4,] 4 4
[5,] 5 5
  [,1] [,2] [,3] [,4] [,5]
x    1    2    3    4    5
y    1    2    3    4    5


# Data Types - Factors

In [15]:
# Create Factors
x <- factor(c("yes","yes","no","no"))
print(x)

[1] yes yes no  no 
Levels: no yes


In [17]:
table(x) # Prints the aggregation of the values.

x
 no yes 
  2   2 

In [22]:
print(unclass(x)) # Gives the details of factor x.

[1] 2 2 1 1
attr(,"levels")
[1] "no"  "yes"


In [27]:
# Implicitly R sets levels of factors alphabetically.
# To explicitly Set level of factors
x <- factor(c("yes","yes","no","no"),levels=c("yes","no")) 
print(x)

[1] yes yes no  no 
Levels: yes no


# Data Types - Missing Values

In [37]:
# NaN is NA but NA is not NaN.
x = c(1,2,3,NA,NaN,NA)
print(is.na(x)) # Used to test objects if they are NA.
print(is.nan(x)) # Used to test objects if they are NAN.

[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE
[1] FALSE FALSE FALSE FALSE  TRUE FALSE


# Data Types - DataFrame

In [2]:
# to get row name - row.names()
# to create DataFrame - read.table() or read.csv()
# convert dataframe to matrix - data.matrix()
x <- data.frame(foo = 1:5, status=c(T,F,T,F,T))
print(x)

  foo status
1   1   TRUE
2   2  FALSE
3   3   TRUE
4   4  FALSE
5   5   TRUE


In [6]:
print(nrow(x)) # get the number of rows
print(ncol(x)) # get the number of columns

[1] 5
[1] 2


# Data Type - Names Attributes

In [16]:
# Name Attributes on Vector.
x <- 1:3
print(names(x))
names(x) <- c("foo","bar","norf")
print(x)
print(names(x))

NULL
 foo  bar norf 
   1    2    3 
[1] "foo"  "bar"  "norf"


In [18]:
# Name Attributes on list.
x <- list(a=1,b=2,c=3)
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [21]:
m <- matrix(1:4,nrow = 2,ncol = 2)
dimnames(m) <- list(c("a","b"),c("a","b"))
m

a b
a 1 3
b 2 4

# Reading Tabular Data

In [1]:
# READING DATA : 

# read.table, read.csv for reading tabular data (Both are same.The only diffrence is that the default separtor is comma in csv.)
# readLines for reading lines of text file.
# 'source' for reading in R code files(inverse of dump).
# 'dget' for reading in R code files(inverse of dput).
# 'load' for reading in saved workspace.
# 'unserialize' for reading single R-object in binary format.

In [3]:
# WRITING DATA : 

# write.table
# writeLines
# dump
# dput
# save 
# serialize

In [10]:
x <- read.csv(file = 'OfficeSupplies.csv')

# Reading Large Tables

In [16]:
initial <- read.csv(file = 'OfficeSupplies.csv', nrows = 100) # Read only first 100 rows initally to get the data types of cols.
classes <- sapply(initial,class) # Gets the Data types of cols.
# print(classes)
# Read whole dataset and apply classes manually so that R doesnt have to traverse whole data set
tableall <- read.csv(file = 'OfficeSupplies.csv',colClasses=classes) 
# print(tableall)

# Textual Data Formats

In [18]:
# dput, dump preserve the meta data of dataframe. like the classes of the columns. we do not have to specify when we read it in.
# 'file' opens a connection to the file.
# 'gzfile' opens a connection to the file that is compressed with gzip.
# 'bzfile' opens a connection to the file that is compressed with bzip2.
# 'url' opens a connection to a webpage.
str(file) # gives the description to the functions.

function (description = "", open = "", blocking = TRUE, encoding = getOption("encoding"), 
    raw = FALSE, method = getOption("url.method", "default"))  


In [85]:
con  <- url('https://www.google.com','r')
x <- readLines(con)
print(head(x))

Warning message in readLines(con):
"incomplete final line found on 'https://www.google.com'"


[1] "<!doctype html><html itemscope=\"\" itemtype=\"http://schema.org/WebPage\" lang=\"en-IN\"><head><meta content=\"text/html; charset=UTF-8\" http-equiv=\"Content-Type\"><meta content=\"/images/branding/googleg/1x/googleg_standard_color_128dp.png\" itemprop=\"image\"><title>Google</title><script nonce=\"2q3RyEmEs5HRziX9FtE+jg==\">(function(){window.google={kEI:'0IywXZyaFomVwgPSzLGIBQ',kEXPI:'0,1353747,5662,730,224,510,1065,3151,378,207,1017,54,2133,10,713,90,180,47,21,96,92,26,325,122,188,482,98,11,68,51,155,255,4,1130636,1197735,288,329244,1294,12383,4855,32692,15247,867,18544,3335,2,2,6801,364,3319,5505,224,2212,5948,1119,2,578,728,2431,1362,4323,3698,1270,773,2255,1402,1413,1074,850,1146,9,1963,6196,1719,1808,1976,2044,5762,1,3146,5071,226,2016,38,920,873,1217,1336,1639,2736,1558,1503,2,215,1,415,1141,2099,7194,252,622,2881,21,317,690,429,904,1150,975,1,369,1398,1379,919,992,444,841,8,1633,1163,967,601,11,14,1279,2212,202,323,6,1251,840,324,193,794,680,48,820,3438,109,151,52,1132,

# Assignment Question

In [65]:
df <- read.csv('hw1_data.csv')
df

Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1 
2    36   118      8.0 72   5      2 
3    12   149     12.6 74   5      3 
4    18   313     11.5 62   5      4 
5    NA    NA     14.3 56   5      5 
6    28    NA     14.9 66   5      6 
7    23   299      8.6 65   5      7 
8    19    99     13.8 59   5      8 
9     8    19     20.1 61   5      9 
10   NA   194      8.6 69   5     10 
11    7    NA      6.9 74   5     11 
12   16   256      9.7 69   5     12 
13   11   290      9.2 66   5     13 
14   14   274     10.9 68   5     14 
15   18    65     13.2 58   5     15 
16   14   334     11.5 64   5     16 
17   34   307     12.0 66   5     17 
18    6    78     18.4 57   5     18 
19   30   322     11.5 68   5     19 
20   11    44      9.7 62   5     20 
21    1     8      9.7 59   5     21 
22   11   320     16.6 73   5     22 
23    4    25      9.7 61   5     23 
24   32    92     12.0 61   5     24 
25   NA    66     16.6 57   5     25 
26   NA   266     14.9 58   5     26 
27   NA    NA      8.0 57   5     27 
28   23    13     12.0 67   5     28 
29   45   252     14.9 81   5     29 
30  115   223      5.7 79   5     30 
... ...   ...     ...  ...  ...   ...
124 96    167      6.9 91   9      1 
125 78    197      5.1 92   9      2 
126 73    183      2.8 93   9      3 
127 91    189      4.6 93   9      4 
128 47     95      7.4 87   9      5 
129 32     92     15.5 84   9      6 
130 20    252     10.9 80   9      7 
131 23    220     10.3 78   9      8 
132 21    230     10.9 75   9      9 
133 24    259      9.7 73   9     10 
134 44    236     14.9 81   9     11 
135 21    259     15.5 76   9     12 
136 28    238      6.3 77   9     13 
137  9     24     10.9 71   9     14 
138 13    112     11.5 71   9     15 
139 46    237      6.9 78   9     16 
140 18    224     13.8 67   9     17 
141 13     27     10.3 76   9     18 
142 24    238     10.3 68   9     19 
143 16    201      8.0 82   9     20 
144 13    238     12.6 64   9     21 
145 23     14      9.2 71   9     22 
146 36    139     10.3 81   9     23 
147  7     49     10.3 69   9     24 
148 14     20     16.6 63   9     25 
149 30    193      6.9 70   9     26 
150 NA    145     13.2 77   9     27 
151 14    191     14.3 75   9     28 
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

In [56]:
mean(df[!is.na(df[,1]),1])

[1] 42.12931

In [74]:
x  <- df[,1] > 31 & df[,4] > 90
x

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE    NA    NA FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE
 [73] FALSE FALSE    NA FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE FALSE    NA FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[121]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [79]:
z <- df[x,]

In [84]:
z  <- z[!is.na.data.frame(z$Solar.R),]
z

Ozone Solar.R Wind Temp Month Day
69   97   267     6.3  92   7      8 
70   97   272     5.7  92   7      9 
120  76   203     9.7  97   8     28 
121 118   225     2.3  94   8     29 
122  84   237     6.3  96   8     30 
123  85   188     6.3  94   8     31 
124  96   167     6.9  91   9      1 
125  78   197     5.1  92   9      2 
126  73   183     2.8  93   9      3 
127  91   189     4.6  93   9      4

In [86]:
mean(z$Solar.R)

[1] 212.8

In [107]:
max(df[(df[,5] == 5),1],na.rm = TRUE)

[1] 115

# Control Structures

## if & if-else

In [12]:
x <- 15

In [13]:
if(x>10){
    x  <- 100
}
x

[1] 100

In [14]:
x <- if(x>10) 150
x

[1] 150

In [15]:
if(x>10){
    x <- 110
}else{
    x <- 0
}
x

[1] 110

In [16]:
x <- if(x>10){
    10
} else {
    0
}
x

[1] 10

## For Loops

In [17]:
for(i in 1:10){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [18]:
x <- c("a","b","c","d","e")

In [23]:
for(i in 1:5){
    print(x[i])
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"


In [24]:
for(i in seq_along(x)){
    print(x[i])
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"


In [25]:
for(letter in x){
    print(letter)
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"


In [26]:
x <- matrix(1:10,nrow = 2,ncol = 5)

In [29]:
for(i in seq_len(nrow(x))){
    for(j in seq_len(ncol(x))){
        print(x[i,j])
    }
}

[1] 1
[1] 3
[1] 5
[1] 7
[1] 9
[1] 2
[1] 4
[1] 6
[1] 8
[1] 10


## While Loop

In [30]:
count <- 0
while(count<=10){
    print(count)
    count <- count+1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [31]:
# 'next' to skip the iteration

# Functions

In [32]:
add2 <- function(x,y){
    x+y # R returns whatever last expresssion is there in the fuction body. 
}

In [33]:
add2(5,3)

[1] 8

In [38]:
above10 <- function(x,n = 10){
    use <- x>n
    x[use]
}

In [40]:
above10(c(1,2,3,4,5,10,15,20),10)
above10(c(1,2,3,4,5,10,15,20))

[1] 15 20

[1] 15 20

In [46]:
meancolumn <- function(x,removeNA = TRUE){
    nc <- ncol(x)
    means <- numeric(nc)
    for(i in 1:nc){
        means[i] <- mean(x[,i],na.rm = removeNA)
    }
    means
}

In [47]:
x <- matrix(1:10,nrow = 2,ncol = 5)
x
meancolumn(x)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[1] 1.5 3.5 5.5 7.5 9.5