# Data Types - Matrices

In [12]:
# Creating Matrices

# Method 1
x <- matrix(nrow=3,ncol=3)
print(x)
print(dim(x))
print(attributes(x))

# Method 2
x <- matrix(1:9,nrow = 3,ncol = 3)
print(x)

# Method 3
m <- 1:10
dim(m) <- c(2,5)
print(m)

# Method 4
x <- 1:5
y <- 1:5
m <- cbind(x,y)
print(m)
m <- rbind(x,y)
print(m)

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[3,]   NA   NA   NA
[1] 3 3
$dim
[1] 3 3

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
     x y
[1,] 1 1
[2,] 2 2
[3,] 3 3
[4,] 4 4
[5,] 5 5
  [,1] [,2] [,3] [,4] [,5]
x    1    2    3    4    5
y    1    2    3    4    5


# Data Types - Factors

In [15]:
# Create Factors
x <- factor(c("yes","yes","no","no"))
print(x)

[1] yes yes no  no 
Levels: no yes


In [17]:
table(x) # Prints the aggregation of the values.

x
 no yes 
  2   2 

In [22]:
print(unclass(x)) # Gives the details of factor x.

[1] 2 2 1 1
attr(,"levels")
[1] "no"  "yes"


In [27]:
# Implicitly R sets levels of factors alphabetically.
# To explicitly Set level of factors
x <- factor(c("yes","yes","no","no"),levels=c("yes","no")) 
print(x)

[1] yes yes no  no 
Levels: yes no


# Data Types - Missing Values

In [37]:
# NaN is NA but NA is not NaN.
x = c(1,2,3,NA,NaN,NA)
print(is.na(x)) # Used to test objects if they are NA.
print(is.nan(x)) # Used to test objects if they are NAN.

[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE
[1] FALSE FALSE FALSE FALSE  TRUE FALSE


# Data Types - DataFrame

In [2]:
# to get row name - row.names()
# to create DataFrame - read.table() or read.csv()
# convert dataframe to matrix - data.matrix()
x <- data.frame(foo = 1:5, status=c(T,F,T,F,T))
print(x)

  foo status
1   1   TRUE
2   2  FALSE
3   3   TRUE
4   4  FALSE
5   5   TRUE


In [6]:
print(nrow(x)) # get the number of rows
print(ncol(x)) # get the number of columns

[1] 5
[1] 2


# Data Type - Names Attributes

In [16]:
# Name Attributes on Vector.
x <- 1:3
print(names(x))
names(x) <- c("foo","bar","norf")
print(x)
print(names(x))

NULL
 foo  bar norf 
   1    2    3 
[1] "foo"  "bar"  "norf"


In [18]:
# Name Attributes on list.
x <- list(a=1,b=2,c=3)
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [21]:
m <- matrix(1:4,nrow = 2,ncol = 2)
dimnames(m) <- list(c("a","b"),c("a","b"))
m

a b
a 1 3
b 2 4